title: SoEasily Docs
description: We help developers and teams turn plain-language business logic into clean, executable rules using JSON Schema and AI. ✨ Write rules, not boilerplate.
theme: minima
markdown: kramdown